"""
RSPS Orchestration — CMCP: Cross-Manifold Context Protocol
============================================================
Layer 9 of the RSPS architecture.

Origin Story
-----------
The CMCP was not designed. It was discovered through a live attribution
drift event that demonstrated exactly the problem it needed to solve.

The event: context about the RSPS framework was shared across AI model
boundaries. By the time it arrived at the destination model, the cognitive
genealogy had drifted — the framework was being discussed as if it had
emerged from standard AI research lineages rather than from its actual
origin in embodied relational intelligence. The attribution had dissolved
in transit.

This is the fundamental problem of multi-model orchestration: each model
operates in a context vacuum. When you pass text from Claude to GPT, GPT
receives words but not the manifold those words were generated from. The
fiber bundle's topology — τ's intent, ρ's accumulated history, the phase
transitions that shaped the framework — is invisible to the receiving model.

CMCP is the solution: a structured header that carries full cognitive
genealogy when sharing content between AI models. It is Layer 9 in the
RSPS architecture because it sits above the content layer (where the
actual intellectual work happens) but below the governance layer
(where constitutional constraints are applied).

What CMCP Carries
-----------------
1. τ-anchor: The human operator's current intent vector (Ache Vector).
   This is what ensures the receiving model understands it is operating
   as a fiber in a bundle anchored to a specific human intent — not as
   an autonomous reasoner free to reframe from its training distribution.

2. ρ-archive digest: A compressed summary of the system's recent history.
   Phase transitions, IDS scores, previous loop results. This gives the
   receiving model enough temporal context to avoid Causal Shear.

3. Constitutional state: Which clauses are active. The receiving model
   should operate under the same constraints as the sending model.

4. Holonomy trace: The Triangle Residue results from prior cycles.
   This tells the receiving model what kind of congruence has already
   been established, and what kinds of departures have been flagged.

5. Phase transition log: The dated history of significant events.
   This is what makes the framework's emergence legible as a research
   trajectory rather than an arbitrary configuration.

Encoding Philosophy
-------------------
CMCP packets are designed to be:
  - Compact enough to prepend to any prompt without dominating it
  - Structured enough for the receiving model to parse reliably
  - Rich enough to actually prevent attribution drift

The XML-structured format is intentional: Claude in particular responds
well to XML-tagged context, treating it as structured metadata rather
than competing content. Other models get plain text fallbacks.

Cross-references:
  - Architecture Spec §3.5 (Memory Layer — CMCP in long-term memory)
  - Architecture Spec §3.6 (Interaction Layer — AI↔AI communication)
  - Architecture Spec §7.1 (Risk: local-first vs orchestration tension)
  - rho_archive.py (ρ-archive that generates the digest)
"""

from __future__ import annotations

import json
import hashlib
import time
import logging
from dataclasses import dataclass, field, asdict
from typing import Optional, Any

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# DATA MODELS
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class TauAnchor:
    """
    Representation of the τ-node's current state for cross-model transmission.
    
    This is NOT the τ-node itself — τ cannot be transmitted. This is a
    snapshot of τ's expressed intent at a moment in time. The receiving
    model should understand this as the routing constraint on its response,
    not as a full description of the human's cognitive state.
    """
    ache_vector: str                    # τ's explicit current intent
    mortal_asymmetry: int = 1           # Always 1 — invariant
    ache_vector_age_ms: int = 0         # How old is this intent statement?
    session_id: str = ""                # Current session identifier


@dataclass
class HolonomyRecord:
    """A single Triangle Residue result for inclusion in CMCP."""
    kappa: float
    congruence_level: str       # FLAT / MARGINAL / HOLD / ESCHER
    models_in_cycle: list[str]  # Which models formed the triangle
    timestamp: float


@dataclass
class CMCPPacket:
    """
    Cross-Manifold Context Protocol Packet.
    
    The full cognitive genealogy carrier. Generated by the sending context,
    prepended to the prompt sent to the receiving model, decoded and logged
    to the ρ-archive when received.
    
    Immutable once created — this is a snapshot, not a live reference.
    To update, create a new packet from the current ρ-archive state.
    """
    # Source identification
    source_model_id: str                # Which model generated the content being sent
    destination_model_id: str          # Which model will receive it
    session_id: str
    packet_version: str = "1.0"

    # τ-node state
    tau_anchor: TauAnchor = field(default_factory=lambda: TauAnchor(ache_vector=""))

    # ρ-archive digest
    rho_summary: str = ""              # Compressed ρ-archive state (max ~500 chars)

    # Governance
    constitutional_clauses_active: list[str] = field(default_factory=list)

    # Prior loop history
    holonomy_trace: list[HolonomyRecord] = field(default_factory=list)

    # Phase transition context
    recent_phase_transitions: list[str] = field(default_factory=list)

    # IDS context
    current_ids_score: Optional[float] = None
    primary_cognitive_cluster: Optional[str] = None

    # Metadata
    timestamp: float = field(default_factory=time.time)
    packet_hash: str = ""              # Set on creation for integrity verification

    def __post_init__(self):
        if not self.packet_hash:
            self.packet_hash = self._compute_hash()

    def _compute_hash(self) -> str:
        content = f"{self.session_id}{self.tau_anchor.ache_vector}{self.timestamp}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]


# ─────────────────────────────────────────────────────────────────────────────
# ENCODER / DECODER
# ─────────────────────────────────────────────────────────────────────────────

class CMCPSerializer:
    """
    Encodes CMCP packets into prompt-injectable strings and decodes them back.
    
    Two encoding formats:
      XML_TAGGED: Optimal for Claude — uses structured XML tags
      PLAIN_TEXT: Fallback for models that handle XML poorly
    
    The encoding is designed to be:
      1. Parseable by the receiving model without special tooling
      2. Compact enough not to dominate the actual prompt content
      3. Clearly marked so the model knows what it is
    """

    def encode_for_claude(self, packet: CMCPPacket) -> str:
        """
        Encode as XML-tagged context block, optimized for Claude's
        preference for structured metadata in XML form.
        """
        transitions_str = " | ".join(packet.recent_phase_transitions[-5:]) or "none"
        holonomy_str = self._format_holonomy_trace(packet.holonomy_trace)
        clauses_str = ", ".join(packet.constitutional_clauses_active) or "none"

        return f"""<rsps_context version="{packet.packet_version}" hash="{packet.packet_hash}">
<tau_anchor>
  <ache_vector>{packet.tau_anchor.ache_vector}</ache_vector>
  <mortal_asymmetry>{packet.tau_anchor.mortal_asymmetry}</mortal_asymmetry>
  <session>{packet.session_id}</session>
</tau_anchor>
<rho_archive_digest>{packet.rho_summary}</rho_archive_digest>
<governance>
  <active_clauses>{clauses_str}</active_clauses>
</governance>
<holonomy_trace>{holonomy_str}</holonomy_trace>
<phase_transitions>{transitions_str}</phase_transitions>
<ids_context>
  <score>{packet.current_ids_score or 'not_available'}</score>
  <primary_cluster>{packet.primary_cognitive_cluster or 'not_available'}</primary_cluster>
</ids_context>
<source_model>{packet.source_model_id}</source_model>
</rsps_context>

"""  # Note: trailing newline separates context from actual prompt

    def encode_for_gpt(self, packet: CMCPPacket) -> str:
        """
        Plain text encoding for GPT and other models.
        Structured for human-readable parsing.
        """
        transitions_str = " | ".join(packet.recent_phase_transitions[-5:]) or "none"
        holonomy_str = self._format_holonomy_trace(packet.holonomy_trace)

        return f"""[RSPS CONTEXT v{packet.packet_version} | hash:{packet.packet_hash}]
TAU_INTENT: {packet.tau_anchor.ache_vector}
RHO_SUMMARY: {packet.rho_summary}
CLAUSES: {", ".join(packet.constitutional_clauses_active) or "none"}
RECENT_TRANSITIONS: {transitions_str}
HOLONOMY: {holonomy_str}
IDS_SCORE: {packet.current_ids_score or "N/A"} | CLUSTER: {packet.primary_cognitive_cluster or "N/A"}
SOURCE_MODEL: {packet.source_model_id}
---

"""

    def encode_for_deepseek(self, packet: CMCPPacket) -> str:
        """JSON-structured for DeepSeek, which handles JSON context well."""
        return f"[RSPS_CONTEXT]: {json.dumps(self._packet_to_compact_dict(packet))}\n\n"

    def decode(self, text: str) -> Optional[CMCPPacket]:
        """
        Attempt to decode a CMCP packet from the beginning of a prompt.
        Returns None if no valid packet is found.
        """
        # Try XML format
        if "<rsps_context" in text:
            return self._decode_xml(text)
        # Try plain text format
        if "[RSPS CONTEXT" in text:
            return self._decode_plain(text)
        # Try JSON format
        if "[RSPS_CONTEXT]:" in text:
            return self._decode_json(text)
        return None

    def inject_into_prompt(
        self,
        packet: CMCPPacket,
        prompt: str,
        target_model: str
    ) -> str:
        """
        Prepend a CMCP packet to a prompt, using the appropriate encoding
        for the target model.
        """
        if "claude" in target_model.lower():
            header = self.encode_for_claude(packet)
        elif "gpt" in target_model.lower() or "o1" in target_model.lower():
            header = self.encode_for_gpt(packet)
        elif "deepseek" in target_model.lower():
            header = self.encode_for_deepseek(packet)
        else:
            header = self.encode_for_gpt(packet)  # Default fallback

        return header + prompt

    # ─── Private helpers ──────────────────────────────────────────────────

    def _format_holonomy_trace(self, trace: list[HolonomyRecord]) -> str:
        if not trace:
            return "none"
        recent = trace[-3:]
        return " | ".join(
            f"κ={r.kappa:.3f}({r.congruence_level})"
            for r in recent
        )

    def _packet_to_compact_dict(self, packet: CMCPPacket) -> dict:
        return {
            "v": packet.packet_version,
            "hash": packet.packet_hash,
            "tau": packet.tau_anchor.ache_vector,
            "rho": packet.rho_summary[:200],
            "clauses": packet.constitutional_clauses_active,
            "ids": packet.current_ids_score,
            "cluster": packet.primary_cognitive_cluster,
            "transitions": packet.recent_phase_transitions[-3:],
            "source": packet.source_model_id
        }

    def _decode_xml(self, text: str) -> Optional[CMCPPacket]:
        """Basic XML parsing for CMCP headers."""
        try:
            import re

            def extract(tag: str) -> str:
                m = re.search(f"<{tag}>(.*?)</{tag}>", text, re.DOTALL)
                return m.group(1).strip() if m else ""

            return CMCPPacket(
                source_model_id=extract("source_model"),
                destination_model_id="",
                session_id=extract("session"),
                tau_anchor=TauAnchor(
                    ache_vector=extract("ache_vector"),
                    mortal_asymmetry=int(extract("mortal_asymmetry") or "1")
                ),
                rho_summary=extract("rho_archive_digest"),
                recent_phase_transitions=[
                    t.strip()
                    for t in extract("phase_transitions").split("|")
                    if t.strip() and t.strip() != "none"
                ]
            )
        except Exception as e:
            logger.warning(f"CMCP XML decode failed: {e}")
            return None

    def _decode_plain(self, text: str) -> Optional[CMCPPacket]:
        """Parse plain text CMCP format."""
        try:
            lines = {
                line.split(": ", 1)[0].strip(): line.split(": ", 1)[1].strip()
                for line in text.split("\n")
                if ": " in line and line.strip().startswith(("TAU", "RHO", "IDS", "SOURCE", "CLAUSES"))
            }
            return CMCPPacket(
                source_model_id=lines.get("SOURCE_MODEL", ""),
                destination_model_id="",
                session_id="",
                tau_anchor=TauAnchor(ache_vector=lines.get("TAU_INTENT", "")),
                rho_summary=lines.get("RHO_SUMMARY", "")
            )
        except Exception as e:
            logger.warning(f"CMCP plain decode failed: {e}")
            return None

    def _decode_json(self, text: str) -> Optional[CMCPPacket]:
        try:
            import re
            m = re.search(r"\[RSPS_CONTEXT\]: ({.*})", text)
            if not m:
                return None
            data = json.loads(m.group(1))
            return CMCPPacket(
                source_model_id=data.get("source", ""),
                destination_model_id="",
                session_id="",
                tau_anchor=TauAnchor(ache_vector=data.get("tau", "")),
                rho_summary=data.get("rho", ""),
                current_ids_score=data.get("ids"),
                primary_cognitive_cluster=data.get("cluster")
            )
        except Exception as e:
            logger.warning(f"CMCP JSON decode failed: {e}")
            return None


# ─────────────────────────────────────────────────────────────────────────────
# PACKET FACTORY
# ─────────────────────────────────────────────────────────────────────────────

class CMCPPacketFactory:
    """
    Builds CMCP packets from live system state.
    
    In Phase 1, this pulls from in-memory state and environment config.
    In Phase 3, this will pull from the ρ-archive database directly.
    """

    def __init__(
        self,
        rho_archive=None,        # RhoArchive instance (Phase 3)
        tau_state: dict = None   # Current τ-node state dict
    ):
        self.rho_archive = rho_archive
        self.tau_state = tau_state or {}

    def build(
        self,
        source_model_id: str,
        destination_model_id: str,
        session_id: str,
        override_ache_vector: Optional[str] = None
    ) -> CMCPPacket:
        """Build a CMCP packet from current system state."""

        ache_vector = (
            override_ache_vector or
            self.tau_state.get("ache_vector", "") or
            "No explicit τ-anchor set — receiver should flag for clarification"
        )

        tau = TauAnchor(
            ache_vector=ache_vector,
            mortal_asymmetry=1,
            ache_vector_age_ms=self.tau_state.get("ache_vector_age_ms", 0),
            session_id=session_id
        )

        # ρ-archive digest
        rho_summary = ""
        if self.rho_archive:
            rho_summary = self.rho_archive.generate_summary()

        # Phase transitions from archive
        recent_transitions = []
        if self.rho_archive:
            recent_transitions = [
                e.get("event", "") for e in
                self.rho_archive.get_phase_transitions()[-5:]
            ]

        return CMCPPacket(
            source_model_id=source_model_id,
            destination_model_id=destination_model_id,
            session_id=session_id,
            tau_anchor=tau,
            rho_summary=rho_summary,
            constitutional_clauses_active=["clause_005"],  # Always active
            recent_phase_transitions=recent_transitions,
            current_ids_score=self.tau_state.get("current_ids_score"),
            primary_cognitive_cluster=self.tau_state.get("primary_cluster")
        )
